### ISSUE TITLE
add safe family of mp_encode_* functions

### ISSUE THREAD

**Issue by nshy** [tarantool/msgpuck#26]
It would be convenient to have safe variant of every mp_encode_* function. For example:
```c
/** 
 Same as mp_encode_uint but if size of output is larger then buffer size `size` then 
 don't write anything. In any case the return value is size of encoded `num`. 
*/
size_t mp_nencode_uint(char *data, size_t size, uint64_t num);
```

First with the help of this function family we can easily encode truncated MsgPack when encoded result is larger then output buffer. Second the same encoding code can be used to calculate output size if one just call it with `data == NULL` and `size == 0`. 

The second benefit can help to deduplicate code in cases like [`fr_encode_log_entry`](https://github.com/tarantool/tarantool-ee/blob/34391538b9e774b61258aa15725154a71f4b3464/src/box/flightrec.c#L237) when we first calculate MsgPack size to find required output buffer size.

These functions are similar to `snprintf` thus the proposed `n` in naming.

**Comment by alyapunov** [comment]
Fixed in 89cadaadbb55a8d8c8a81c184dc331f1a236a914
